# Generated by Django 5.0.1 on 2024-02-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
    ]
