# Generated by Django 5.0.1 on 2024-03-08 08:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_forumpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Nội dung'),
        ),
    ]
