# Generated by Django 5.0.1 on 2024-03-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_forumpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=models.TextField(verbose_name='Nội dung'),
        ),
    ]
