# Generated by Django 5.0.1 on 2024-03-08 08:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_forumpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
