# Generated by Django 5.0.1 on 2024-03-18 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(max_length=500)),
                ('anothername', models.CharField(max_length=200)),
                ('img', models.URLField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('isCompleted', models.BooleanField()),
                ('workerid', models.IntegerField(default=-1)),
                ('note', models.TextField()),
                ('quantityVol', models.IntegerField()),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(default=-900)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(db_index=True, default='nullusername', max_length=40, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='nullemail@an.com', max_length=100, unique=True)),
                ('password', models.CharField(default='nullpassword', max_length=40)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('date_join', models.DateTimeField(default=django.utils.timezone.now)),
                ('img_avatar', models.URLField(max_length=100, null=True)),
                ('img_background', models.URLField(max_length=100, null=True)),
                ('role_id', models.ForeignKey(default=-900, on_delete=django.db.models.deletion.CASCADE, to='app.role')),
            ],
        ),
    ]
