# Generated by Django 5.0.1 on 2024-04-13 00:49

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('content', ckeditor.fields.RichTextField(default='')),
                ('view', models.IntegerField(default=0)),
                ('date_upload', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupname', models.CharField(db_index=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(default=-900, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('anothername', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(null=True, upload_to='books_images/')),
                ('author', models.CharField(max_length=100, null=True)),
                ('artist', models.CharField(max_length=100, null=True)),
                ('isCompleted', models.BooleanField(blank=True, null=True)),
                ('workerid', models.IntegerField(default=-1, null=True)),
                ('note', models.TextField(null=True)),
                ('quantityVol', models.IntegerField(default=0)),
                ('dateUpload', models.DateField(null=True)),
                ('dateUpdate', models.DateTimeField(null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='books', to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamrole', models.CharField(db_index=True, default='member', max_length=40)),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.group')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('date_join', models.DateTimeField(default=django.utils.timezone.now)),
                ('img_avatar', models.ImageField(null=True, upload_to='avatar_images/')),
                ('img_background', models.ImageField(blank=True, null=True, upload_to='background_images/')),
                ('img_background_position', models.IntegerField(default=0)),
                ('role_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_comments', to='app.chapter')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('img', models.ImageField(upload_to='volume_images/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='app.book')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='app.volume'),
        ),
    ]
