# Generated by Django 5.0.1 on 2024-04-02 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(null=True, upload_to='books_images/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='role_id',
            field=models.ForeignKey(default=-900, on_delete=django.db.models.deletion.CASCADE, to='app.role'),
        ),
    ]
