# Generated by Django 5.0.2 on 2024-03-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_group_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='teamrole',
            field=models.CharField(default='member', max_length=40),
        ),
    ]
