# Generated by Django 5.0.1 on 2024-04-10 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='app.volume'),
            preserve_default=False,
        ),
    ]
