# Generated by Django 5.0.1 on 2024-03-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='anothername',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='artist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantityVol',
            field=models.IntegerField(default=10),
        ),
    ]
