# Generated by Django 5.0.1 on 2024-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_chapter_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='img',
            field=models.ImageField(default=0, upload_to='volume_images/'),
            preserve_default=False,
        ),
    ]
