# Generated by Django 5.0.2 on 2024-03-15 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_group_is_group_admin_member_teamrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_group_admin',
        ),
        migrations.AddField(
            model_name='group',
            name='groupAdmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
