# Generated by Django 5.0.1 on 2024-04-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_volume_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
