# Generated by Django 5.0.1 on 2024-04-02 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_member_user_member_auth_user_member_teamrole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.IntegerField(default=-900, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.role'),
        ),
    ]
