# Generated by Django 5.0.1 on 2024-03-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_book_anothername_alter_book_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isCompleted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
