# Generated by Django 5.0.1 on 2024-04-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_group_description_alter_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='date_join',
        ),
        migrations.AddField(
            model_name='chaptercomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
