# Generated by Django 5.0.1 on 2024-04-04 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_role_role_id_alter_userinfo_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
