# Generated by Django 5.0.1 on 2024-03-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_book_iscompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='workerid',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
