# Generated by Django 5.0.1 on 2024-04-09 07:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_categorybook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('view', models.IntegerField()),
                ('date_upload', models.DateTimeField()),
            ],
        ),
    ]
