# Generated by Django 5.0.1 on 2024-04-11 15:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_chapter_content_alter_chapter_date_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
