# Generated by Django 5.0.1 on 2024-04-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_book_category_book_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dateUpdate',
            field=models.DateTimeField(null=True),
        ),
    ]
