# Generated by Django 5.0.1 on 2024-03-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
