# Generated by Django 5.0.1 on 2024-03-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_img_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
