# Generated by Django 5.0.1 on 2024-03-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_book_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='date',
            new_name='dateUpdate',
        ),
        migrations.AddField(
            model_name='book',
            name='dateUpload',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
